#ifndef RESOURCE_H_INCLUDED
#define RESOURCE_H_INCLUDED
#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDB_BITMAP1 1000
#define IDC_CUR 2000

#define MY_ICON2 3000

#endif // RESOURCE_H_INCLUDED
